---
{{- if .Values.extraEnvVars}}
apiVersion: v1
kind: ConfigMap 
metadata:
  name: {{ include "homebridge.fullname" . }}
  labels:
    {{- include "homebridge.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.extraEnvVars}}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
