---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homebridge.fullname" . }}
  labels:
    {{- include "homebridge.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.pvc.storageClass }}
  accessModes: {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
