---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homebridge.fullname" . }}
  labels:
    {{- include "homebridge.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.pvcs.main.storageClass }}
  accessModes: {{ .Values.pvcs.main.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvcs.main.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homebridge.fullname" . }}-storage-path
  labels:
    {{- include "homebridge.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.pvcs.storagePath.storageClass }}
  accessModes: {{ .Values.pvcs.storagePath.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvcs.storagePath.size }}
