---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homebridge.fullname" . }}
  labels:
    {{- include "homebridge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: {{ .Values.service.protocol }}
      name: http
  selector:
    {{- include "homebridge.selectorLabels" . | nindent 4 }}
